KMK(1)                                                                               simple makefiles for complex tasks                                                                              KMK(1)

NAME
       kmk - framework for writing simple makefiles for complex tasks

SYNOPSIS
       kmk [OPTIONS]

DESCRIPTION
       kmk and its helper tools are an extension to GNU make to ease writing portable Makefile.

       The goals of the kBuild framework:

        - Similar behavior cross all supported platforms.
        - Flexibility, don't create unnecessary restrictions preventing ad-hoc solutions.
        - Makefile can very simple to write and maintain.

       There are four concepts being tried out in the current kBuild incaration:

        - One configuration file for a subtree automatically included.
        - Target configuration templates as the primary mechanism for makefile simplification.
        - Tools and SDKs for helping out the templates with flexibility.
        - Non-recursive makefile method by using sub-makefiles.

       kBuild  does  not provide any facilities for checking compiler/library/header configurations, that's not in its scope. If this is important for your project, check out the autoconf tool in the GNU
       build system. It is possible to use kBuild together with autoconf if you like, but you might just as well use the full GNU package.

       On Debian systems, the kBuild binaries can be found in /usr/bin and its data files in /usr/share/kBuild.

SEE ALSO
       make(1)

HOMEPAGE
       More information about kBuild project can be found at <http://svn.netlabs.org/kbuild/>.

AUTHOR
       kBuild was written by Knut St. Osmundsen <bird-kBuild-spam@anduin.net>.

       This manual page was written by Daniel Baumann <daniel@debian.org>, for the Debian project (but may be used by others).

0.1.98svn2318                                                                                    2009-04-09                                                                                          KMK(1)
